# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yolox.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0byolox.proto\x12\x05yolox\"\x1c\n\x08\x42\x36\x34Image\x12\x10\n\x08\x62\x36\x34image\x18\x01 \x01(\t\"\x1e\n\nPrediction\x12\x10\n\x08\x62\x62ox_arr\x18\x02 \x01(\t2:\n\x05Yolox\x12\x31\n\tInference\x12\x0f.yolox.B64Image\x1a\x11.yolox.Prediction\"\x00\x62\x06proto3')



_B64IMAGE = DESCRIPTOR.message_types_by_name['B64Image']
_PREDICTION = DESCRIPTOR.message_types_by_name['Prediction']
B64Image = _reflection.GeneratedProtocolMessageType('B64Image', (_message.Message,), {
  'DESCRIPTOR' : _B64IMAGE,
  '__module__' : 'yolox_pb2'
  # @@protoc_insertion_point(class_scope:yolox.B64Image)
  })
_sym_db.RegisterMessage(B64Image)

Prediction = _reflection.GeneratedProtocolMessageType('Prediction', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTION,
  '__module__' : 'yolox_pb2'
  # @@protoc_insertion_point(class_scope:yolox.Prediction)
  })
_sym_db.RegisterMessage(Prediction)

_YOLOX = DESCRIPTOR.services_by_name['Yolox']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _B64IMAGE._serialized_start=22
  _B64IMAGE._serialized_end=50
  _PREDICTION._serialized_start=52
  _PREDICTION._serialized_end=82
  _YOLOX._serialized_start=84
  _YOLOX._serialized_end=142
# @@protoc_insertion_point(module_scope)
