# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import yolox_pb2 as yolox__pb2


class YoloxStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inference = channel.unary_unary(
                '/yolox.Yolox/Inference',
                request_serializer=yolox__pb2.B64Image.SerializeToString,
                response_deserializer=yolox__pb2.Prediction.FromString,
                )


class YoloxServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Inference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YoloxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inference': grpc.unary_unary_rpc_method_handler(
                    servicer.Inference,
                    request_deserializer=yolox__pb2.B64Image.FromString,
                    response_serializer=yolox__pb2.Prediction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yolox.Yolox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Yolox(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Inference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yolox.Yolox/Inference',
            yolox__pb2.B64Image.SerializeToString,
            yolox__pb2.Prediction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
